// <auto-generated />
using System;
using Emartim_CRUD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Emartim_CRUD.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Emartim_CRUD.Models.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Carg")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Carg");

                    b.Property<bool>("Situacao")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Situacao");

                    b.HasKey("Id");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("Emartim_CRUD.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Cargo");

                    b.Property<DateTime>("Data_Admissao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Data_Admissao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Nome");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Salario");

                    b.Property<bool>("Situacao")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Situacao");

                    b.HasKey("Id");

                    b.ToTable("Funcionario");
                });
#pragma warning restore 612, 618
        }
    }
}
